### PR TITLE
Allow to provide custom yum repo

### PR DESCRIPTION
**Pull request by mremy**
In order to consolidate the rpm, we should be able to define the repositories.

### CODE REVIEW

**Comment by mcanevet** [comment]
@mremy a lot of module name `manage_repo` the class parameter to do that. Would it be possible to rename `dell_repo` to `manage_repo` to use the "not that official" standard way?

Otherwise +1 to merge this.

**Comment by raphink** [comment]
I would prefer a $repo_ensure parameter, to mark the repo as present or
absent, as that would allow to remove it.

--
Raphaël Pinson
Infrastructure Developer & Trainer
+33 479 26 57 93
+33 781 90 00 79

Camptocamp France
Savoie Technolac
BP 352
48, avenue du Lac du Bourget
73372 Le Bourget-du-Lac, Cedex

**Comment by mremy** [comment]
The source problem is with dell repo often change, and that at the present time, no repo are available for 13 generation server (x10) with rhel7.
But, they are rpm available...
@raphink: One way or another, we need a repo, so I don't think the "repo_ensure" is a good choice.
So, "manage_repo" ?

**Comment by mcanevet** [comment]
@mremy after discussion with @raphink I'd vote for `repo_ensure` parameter so that the official repo could be removed.

**Pull request merged**
